// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IEventRepository is an autogenerated mock type for the IEventRepository type
type IEventRepository struct {
	mock.Mock
}

// InsertEvent provides a mock function with given fields: event, phoneNumber
func (_m *IEventRepository) InsertEvent(event string, phoneNumber string) {
	_m.Called(event, phoneNumber)
}

// NewIEventRepository creates a new instance of IEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEventRepository {
	mock := &IEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
