// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IGenerator is an autogenerated mock type for the IGenerator type
type IGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: phoneNumber
func (_m *IGenerator) Generate(phoneNumber string) (int32, error) {
	ret := _m.Called(phoneNumber)

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int32, error)); ok {
		return rf(phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(string) int32); ok {
		r0 = rf(phoneNumber)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGenerator creates a new instance of IGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGenerator {
	mock := &IGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
